### ISSUE TITLE
Cannot run program "mp-compiler": error=2, No such file or directory

### ISSUE THREAD

**Issue by anuruddhal** [metaparticle-io/package#129]
I tried the [java tutorial](https://metaparticle.io/tutorials/java/) and getting following error when trying to deploy the artifacts to kubernetes:

**OS** : Mac OS
**Docker**: Docker for mac 18.05.0-ce
**Kubernetes**: 
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:05:37Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
$ mvn exec:java -Dexec.mainClass=io.metaparticle.tutorial.Main
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=1024m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building metaparticle-package-tutorial 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ metaparticle-package-tutorial ---
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=1024m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building metaparticle-package-tutorial 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (add_sources) @ metaparticle-package-tutorial ---
[INFO] Source directory: /Users/anuruddha/workspace/ballerinax/package/tutorials/java/src/main/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ metaparticle-package-tutorial ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/anuruddha/workspace/ballerinax/package/tutorials/java/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ metaparticle-package-tutorial ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-test-source (add_test_sources) @ metaparticle-package-tutorial ---
[INFO] Test Source directory: /Users/anuruddha/workspace/ballerinax/package/tutorials/java/src/test/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ metaparticle-package-tutorial ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/anuruddha/workspace/ballerinax/package/tutorials/java/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ metaparticle-package-tutorial ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ metaparticle-package-tutorial ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ metaparticle-package-tutorial ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default) @ metaparticle-package-tutorial ---
[INFO] commons-lang3-3.4.jar already exists in destination.
[INFO] slf4j-api-1.7.22.jar already exists in destination.
[INFO] logging-interceptor-3.3.1.jar already exists in destination.
[INFO] okio-1.8.0.jar already exists in destination.
[INFO] jackson-core-2.7.2.jar already exists in destination.
[INFO] jsr305-1.3.9.jar already exists in destination.
[INFO] okhttp-urlconnection-3.3.1.jar already exists in destination.
[INFO] j2objc-annotations-1.1.jar already exists in destination.
[INFO] animal-sniffer-annotations-1.14.jar already exists in destination.
[INFO] jackson-datatype-joda-2.7.2.jar already exists in destination.
[INFO] rxjava-1.2.4.jar already exists in destination.
[INFO] azure-annotations-1.2.0.jar already exists in destination.
[INFO] retrofit-2.1.0.jar already exists in destination.
[INFO] gson-2.8.2.jar already exists in destination.
[INFO] error_prone_annotations-2.0.18.jar already exists in destination.
[INFO] guava-23.0.jar already exists in destination.
[INFO] jackson-annotations-2.7.0.jar already exists in destination.
[INFO] converter-jackson-2.1.0.jar already exists in destination.
[INFO] json-20170516.jar already exists in destination.
[INFO] okhttp-3.3.1.jar already exists in destination.
[INFO] client-runtime-1.1.0.jar already exists in destination.
[INFO] joda-time-2.4.jar already exists in destination.
[INFO] metaparticle-java-0.1-SNAPSHOT.jar already exists in destination.
[INFO] metaparticle-package-0.1-SNAPSHOT.jar already exists in destination.
[INFO] adapter-rxjava-2.1.0.jar already exists in destination.
[INFO] jackson-databind-2.7.2.jar already exists in destination.
[INFO] 
[INFO] --- maven-jar-plugin:2.2:jar (default) @ metaparticle-package-tutorial ---
[INFO] 
[INFO] --- maven-jar-plugin:2.2:test-jar (default) @ metaparticle-package-tutorial ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] 
[INFO] --- maven-assembly-plugin:3.1.0:single (assemble-all) @ metaparticle-package-tutorial ---
[INFO] Building jar: /Users/anuruddha/workspace/ballerinax/package/tutorials/java/target/metaparticle-package-tutorial-0.1-SNAPSHOT-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.176 s
[INFO] Finished at: 2018-06-21T10:31:41+05:30
[INFO] Final Memory: 73M/1237M
[INFO] ------------------------------------------------------------------------
java.io.IOException: Cannot run program "mp-compiler": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at io.metaparticle.Util.handleErrorExec(Util.java:26)
        at io.metaparticle.MetaparticleExecutor.run(MetaparticleExecutor.java:137)
        at io.metaparticle.Metaparticle.Containerize(Metaparticle.java:140)
        at io.metaparticle.tutorial.Main.main(Main.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 12 more
java.io.IOException: Cannot run program "mp-compiler": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at io.metaparticle.Util.handleErrorExec(Util.java:26)
        at io.metaparticle.MetaparticleExecutor.logs(MetaparticleExecutor.java:34)
        at io.metaparticle.Metaparticle.Containerize(Metaparticle.java:141)
        at io.metaparticle.tutorial.Main.main(Main.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 12 more
java.io.IOException: Cannot run program "mp-compiler": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:485)
        at io.metaparticle.Util.handleErrorExec(Util.java:26)
        at io.metaparticle.MetaparticleExecutor.cancel(MetaparticleExecutor.java:30)
        at io.metaparticle.Metaparticle.lambda$Containerize$0(Metaparticle.java:137)
        at io.metaparticle.Util$1.run(Util.java:50)
        at io.metaparticle.Metaparticle.Containerize(Metaparticle.java:142)
        at io.metaparticle.tutorial.Main.main(Main.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 14 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.590 s
[INFO] Finished at: 2018-06-21T10:31:43+05:30
[INFO] Final Memory: 23M/981M
[INFO] ------------------------------------------------------------------------
```

**Comment by anuruddhal** [comment]
My bad I didn't install [mp-compiler](https://github.com/metaparticle-io/metaparticle-ast/releases).
