### ISSUE TITLE
Container detection requires privileged access

### ISSUE THREAD

**Issue by wagoodman** [metaparticle-io/package#39]
Currently you need to run the given `example.py` as root, or else you'll see a permission error:

```python
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    hihi()
  File "/home/wagoodman/github/package/python/metaparticle.py", line 70, in wrapper
    if is_in_docker_container():
  File "/home/wagoodman/github/package/python/metaparticle.py", line 13, in is_in_docker_container
    with open('/proc/1/cgroup', 'r+t') as f:
PermissionError: [Errno 13] Permission denied: '/proc/1/cgroup'
```

**Comment by wagoodman** [comment]
I seem to have been the only one with this issue, clearly it was 2am user error :)
